Repository xbmc/kodi-tv, pull requests merged in 2023-12, with the labels that each got.

#688 Create Sponsor “osuosl”
  src/data/yaml/sponsor/osuosl.yaml
  static/images/sponsors/osllogo-web_0.png
Labels: decap-cms/draft

#695 Update Sponsor “osuosl”
  src/data/yaml/sponsor/osuosl.yaml
Labels: decap-cms/pending_publish

#697 Update Distribution “android”
  src/data/yaml/distribution/android.yaml
Labels: decap-cms/pending_publish

#704 Update Distribution “linux”
  src/data/yaml/distribution/linux.yaml
Labels: decap-cms/pending_publish

#702 Update Distribution “tvos”
  src/data/yaml/distribution/tvos.yaml
Labels: decap-cms/pending_publish

#701 Update Distribution “raspberry-pi”
  src/data/yaml/distribution/raspberry-pi.yaml
Labels: decap-cms/pending_publish

#700 Update Distribution “macos”
  src/data/yaml/distribution/macos.yaml
Labels: decap-cms/pending_publish

#703 Update Distribution “windows”
  src/data/yaml/distribution/windows.yaml
Labels: decap-cms/pending_publish

#698 Update Distribution “ios”
  src/data/yaml/distribution/ios.yaml
Labels: decap-cms/pending_publish

#712 Create Post “kodi-21-0-omega-beta-2/index”
  src/content/article/kodi-21-0-omega-beta-2/index.md
Labels: netlify-cms/pending_publish
